#Python as a Calculator
a=int(input("Enter the first number:"))
b=int(input("Enter the second number:"))
c=int(input("Enter the third number:"))
print("a + b = ",a+b)
print("a - b = ",a-b)
print("a * b = ",a*b)
print("a / b = ",a/b)
print("a % b = ",a%b)
print("a // b = ",a//b)
print("a ** b = ",a**b)
print("a + b * c = ",a+b*c)
print("(a + b) * c = ",(a+b)*c)
print("a / b + c = ",a/b+c)
print("a / (b + c) = ",a/(b+c))
print("a + b / c = ",a+b/c)
print("(a + b) / c = ",(a+b)/c)